### ISSUE TITLE
The follow up components after the header component either sits hidden or overalps

### ISSUE THREAD

**Issue by kekir** [CodyHouse/cd-breadcrumbs-changelog#1]
The problem I have:
Scenario: On the start of my page I have a header component, after that I want my second component to sit exactly flush with the first (i.e. the header component).
Result: I am not able to do that, out of the box.
What happens: The second component overlaps the header

Fix I implement: I absolutely position the second element in the component's scss file like this
Result: it works
What happens: The third component starts to overlap the second when sitting flush

Documentation: I know about the position utility classes but in this case, it failed as there is no position class that calculates the height and position of the previous component.

![Screenshot (164)](https://user-images.githubusercontent.com/2199948/154370713-5bf34ea9-f484-49a4-a4c1-7521d7ce0424.png)
![Screenshot (165)](https://user-images.githubusercontent.com/2199948/154370721-96702c55-ae09-406f-be0a-f8cbf1c2b65d.png)
![Screenshot (166)](https://user-images.githubusercontent.com/2199948/154370727-f0044283-0f7b-4429-83cd-b94909becd14.png)
![Screenshot (167)](https://user-images.githubusercontent.com/2199948/154370731-cccca790-5c78-4456-87ef-9db9a542cac5.png)

**Comment by claudia-romano** [comment]
Hi there,
I just tested it and I was not able to recreate the issue. I used the Main Header and the Breadcrumbs components and there's no overlap (as it should be):
<img width="1436" alt="Screenshot 2022-02-18 at 08 07 38" src="https://user-images.githubusercontent.com/5512545/154634808-fb49f161-9220-443c-9db0-32f3358f9d4f.png">

Please try recreating the issue without your custom CSS. If you can't (as I wasn't) then there are some issues with the custom code you are using. Cheers!

**Comment by kekir** [comment]
Hi Claudia,
Thanks for the reply but actually I am not using any custom code in the
issue that I have generated. The explanation about the custom code was just
an experiment on my side to make it work.
Although I am using webpack and i am generating the frontend.js as
explained in the documentation. But all that aspect of JS bundling works
fine, no issues there but i am not sure otherwise.

thanks keki

**Comment by kekir** [comment]
Hi Caludia,
I had a container calls used wrongly in my code and that has fixed it all
thanks keki
